name: alquran
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.3
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.2
  get_it: ^7.1.3
  flutter_bloc: ^8.1.1
  path_provider: ^2.0.2
  flutter_scroll_to_top: ^2.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

 
